version: '2'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    volumes:
      - ./mysql:/var/lib/mysql
    expose:
      - "3306" #for service mysql-proxy
    ports:
      - "3307:3306" #for external connection
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: BlenderBot
      MYSQL_USER: root
      MYSQL_PASSWORD: password
  blenderbot:
    restart: always
    build: "./"
    depends_on:
      - mysql

